Repository pioneerspacesim/pioneer, pull requests merged in 2019-06, with the labels that each got.

#4606 Basic Atmospheric heating re-enabled
  src/Player.cpp
  src/Player.h
  src/Ship.cpp
  src/Ship.h
  src/collider/CollisionContact.h
  src/collider/CollisionSpace.cpp
  src/collider/Geom.cpp
  src/collider/Geom.h
Labels: Bug fix

#4607 Further Input and WorldView improvements.
  data/lang/input-core/en.json
  data/libs/Equipment.lua
  data/pigui/modules/autopilot-window.lua
  src/DynamicBody.cpp
  src/Input.cpp
  src/KeyBindings.inc.h
  src/LuaGame.cpp
  src/LuaPlayer.cpp
  src/LuaShip.cpp
  src/Ship-AI.cpp
  src/Ship.h
  src/ShipAICmd.h
  src/ShipType.h
  src/WorldView.cpp
  src/WorldView.h
  src/enum_table.cpp
  src/ship/PlayerShipController.cpp
  src/ship/PlayerShipController.h
  src/ship/Propulsion.cpp
  src/ship/Propulsion.h
Labels: Cleanup

#4595 Remove Color from Lua instead use LuaColor as a userdata
  data/libs/Color.lua
  data/libs/ui/PiguiFace.lua
  data/pigui/modules/autopilot-window.lua
  data/pigui/modules/comms.lua
  data/pigui/modules/equipment.lua
  data/pigui/modules/fx-window.lua
  data/pigui/modules/gauges.lua
  data/pigui/modules/map-sector-view.lua
  data/pigui/modules/planetary-info.lua
  data/pigui/modules/radar.lua
  data/pigui/modules/saveloadgame.lua
  data/pigui/modules/settings-window.lua
  data/pigui/modules/ship-internals-window.lua
  data/pigui/modules/time-window.lua
  data/pigui/pigui.lua
  data/pigui/themes/default.lua
  data/pigui/views/game.lua
  data/pigui/views/init.lua
  src/Color.h
  src/LuaColor.cpp
  src/LuaColor.h
  src/LuaPiGui.cpp
  src/LuaVector.cpp
  src/LuaVector2.cpp
  src/Pi.cpp
Labels: Lua API, Optimization

#4576 Refactor game UI, refactor flag handling, move InfoView to pigui.
  .clang-format
  .gitignore
  .travis.yml
  data/modules/DebugShipSpawn/DebugShipSpawn.lua
  data/modules/DebugShipSpawn/DebugShipSpawn.moon
  data/pigui/init.lua
  data/pigui/libs/table.lua
  data/pigui/libs/view-util.lua
  data/pigui/modules/equipment.lua
  data/pigui/modules/flight-ui/gauges.lua
  data/pigui/modules/flight-ui/hyperspace.lua
  data/pigui/modules/flight-ui/indicators.lua
  data/pigui/modules/flight-ui/reticule.lua
  data/pigui/modules/flight-ui/target-scanner.lua
  data/pigui/modules/gauges.lua
  data/pigui/pigui.lua
  data/pigui/views/game.lua
  data/pigui/views/info-view.lua
  scripts/clang-format.sh
  src/GZipFormat.cpp
  src/LuaPiGui.cpp
  src/LuaPushPull.h
  src/LuaUtils.cpp
  src/Pi.cpp
  src/pigui/LuaFlags.h
  src/scenegraph/BinaryConverter.cpp
Labels: Cleanup, Lua API, UI rewrite

#4608 Change landing lights according to #4, rework the NavLights class.
  src/NavLights.cpp
  src/NavLights.h
  src/SpaceStation.cpp
Labels: C++ code, Cosmetic or UI

#4615 Cleanup LuaVector and LuaColor implementations.
  data/pigui/modules/flight-ui/indicators.lua
  src/LuaColor.cpp
  src/LuaVector.cpp
  src/LuaVector2.cpp
Labels: Cleanup

#4616 Use Equatorial Radius when making the frame for a star
  src/Space.cpp
  src/galaxy/SystemBody.h
Labels: Bug fix

#4617 Star rendering optimisation
  src/BaseSphere.cpp
  src/GeoSphere.cpp
  src/Star.cpp
  src/Star.h
  src/fixed.h
Labels: Optimization

#4614 Pigui Model Spinner, move ShipInfo to pigui.
  data/libs/ui/PiguiFace.lua
  data/pigui/libs/table.lua
  data/pigui/modules/info-view/01-ship-info.lua
  data/pigui/modules/info-view/02-personal-info.lua
  data/pigui/pigui.lua
  src/LuaPiGui.cpp
  src/Pi.cpp
  src/pigui/LuaFace.cpp
  src/pigui/LuaFlags.h
  src/pigui/LuaModelSpinner.cpp
  src/pigui/ModelSpinner.cpp
  src/pigui/ModelSpinner.h
  src/pigui/PiGuiLua.cpp
Labels: Lua API, UI rewrite
