Repository pioneerspacesim/pioneer, pull requests merged in 2020-11, with the labels that each got.

#4991 Decreasing the max star size to 0.3
  data/configs/Starfield.ini
Labels: Cosmetic or UI

#4877 Escape pod for the scoop mission
  data/models/misc/escape_pod/escape_pod.model
  data/models/misc/escape_pod/escape_pod_COLL.dae
  data/models/misc/escape_pod/escape_pod_DIFF.dds
  data/models/misc/escape_pod/escape_pod_GLOW.dds
  data/models/misc/escape_pod/escape_pod_HIGH.dae
  data/models/misc/escape_pod/escape_pod_LOW.dae
  data/models/misc/escape_pod/escape_pod_MED.dae
  data/models/misc/escape_pod/escape_pod_NORM.dds
  data/models/misc/escape_pod/escape_pod_SPEC.dds
  data/models/misc/escape_pod/pattern01.dds
Labels: Art

#4995 Refactor Body inheritance tree to remove Object and CityOnPlanet
  src/Beam.cpp
  src/Beam.h
  src/Body.cpp
  src/Body.h
  src/Camera.cpp
  src/CargoBody.cpp
  src/CargoBody.h
  src/CityOnPlanet.cpp
  src/CityOnPlanet.h
  src/DynamicBody.cpp
  src/DynamicBody.h
  src/Game.cpp
  src/Missile.cpp
  src/Missile.h
  src/ModelBody.cpp
  src/Object.h
  src/ObjectViewerView.cpp
  src/Player.cpp
  src/Player.h
  src/Projectile.cpp
  src/Sensors.cpp
  src/Sfx.cpp
  src/Ship-AI.cpp
  src/Ship.cpp
  src/Ship.h
  src/ShipAICmd.cpp
  src/ShipCpanel.cpp
  src/ShipCpanel.h
  src/ShipCpanelMultiFuncDisplays.cpp
  src/ShipCpanelMultiFuncDisplays.h
  src/Space.cpp
  src/Space.h
  src/SpaceStation.cpp
  src/SpaceStation.h
  src/SystemInfoView.cpp
  src/SystemView.cpp
  src/TerrainBody.h
  src/WorldView.cpp
  src/enum_table.cpp
  src/lua/LuaBody.cpp
  src/lua/LuaPiGui.cpp
  src/lua/LuaPlayer.cpp
  src/lua/LuaShip.cpp
  src/ship/CameraController.cpp
  src/ship/Propulsion.cpp
  src/sound/AmbientSounds.cpp
  src/win32/pch.h
Labels: Cleanup

#5027 Add menu music courtesy of franzopow
  AUTHORS.txt
  data/modules/MusicPlayer.lua
  data/music/core/menu/menu_master.ogg
  data/music/core/unexplored/lost_space_explorer.ogg
  data/pigui/views/mainmenu.lua
  src/lua/LuaMusic.cpp
  src/sound/SoundMusic.cpp
  src/sound/SoundMusic.h
Labels: New feature
