Repository pioneerspacesim/pioneer, pull requests merged in 2020-03, with the labels that each got.

#4828 Add histogram to pigui
  data/pigui/pigui.lua
  src/lua/LuaPiGui.cpp
Labels: C++ code

#4842 Improve Mouse Capture Handling
  .github/workflows/clang-format.yml
  data/pigui/libs/modal-win.lua
  data/pigui/views/game.lua
  data/pigui/views/mainmenu.lua
  scripts/clang-format.sh
  src/Input.cpp
  src/Input.h
  src/ModelViewer.cpp
  src/Pi.cpp
  src/graphics/Renderer.cpp
  src/graphics/Renderer.h
  src/pigui/PiGui.cpp
  src/ship/PlayerShipController.cpp
  src/ship/ShipViewController.cpp
  src/ship/ShipViewController.h
Labels: Bug fix, C++ code, Lua code

#4845 Refactor Main Loop Paradigm
  CMakeLists.txt
  contrib/profiler/Profiler.h
  src/GasGiant.cpp
  src/GeoPatchContext.cpp
  src/GeoSphere.cpp
  src/IniConfig.h
  src/Input.cpp
  src/Input.h
  src/Intro.cpp
  src/Intro.h
  src/KeyBindings.cpp
  src/OS.h
  src/ObjectViewerView.cpp
  src/Pi.cpp
  src/Pi.h
  src/SectorView.cpp
  src/SystemView.cpp
  src/WorldView.cpp
  src/core/Application.cpp
  src/core/Application.h
  src/core/CMakeLists.txt
  src/core/GuiApplication.cpp
  src/core/GuiApplication.h
  src/graphics/Graphics.cpp
  src/graphics/opengl/Program.cpp
  src/lua/LuaGame.cpp
  src/lua/LuaInput.cpp
  src/lua/LuaPiGui.cpp
  src/main.cpp
  src/pigui/PiGui.cpp
  src/pigui/PiGui.h
  src/posix/OSPosix.cpp
  src/ship/PlayerShipController.cpp
  src/ship/PlayerShipController.h
  src/ship/ShipViewController.cpp
  src/terrain/TerrainDbg.cpp
  src/win32/OSWin32.cpp
  win32/vs2019/pioneer.vcxproj
  win32/vs2019/pioneer.vcxproj.filters
Labels: C++ code, Design
