Repository pioneerspacesim/pioneer, pull requests merged in 2020-12, with the labels that each got.

#5042 Use new icons in Worldview
  data/icons/icons.svg
  data/pigui/baseui.lua
  data/pigui/libs/forwarded.lua
  data/pigui/modules/flight-ui/body-icons.lua
  data/pigui/modules/system-overview-window.lua
  data/pigui/themes/default.lua
  data/pigui/views/game.lua
  data/pigui/views/mainmenu.lua
  src/galaxy/StarSystemGenerator.cpp
  src/lua/LuaPiGui.cpp
  src/pigui/PerfInfo.cpp
Labels: Cosmetic or UI

#5033 Optimise route rendering
  src/MathUtil.h
  src/SectorView.cpp
  src/SectorView.h
  src/galaxy/Sector.cpp
  src/galaxy/Sector.h
Labels: Optimization, WIP

#5059 BBS advert for soldout commodity
  .tx/config
  data/lang/module-soldout/en.json
  data/modules/SoldOut/SoldOut.lua
Labels: Lua code, New feature

#5075 Significantly Slash Savefile Sizes
  data/libs/SpaceStation.lua
  src/posix/FileSystemPosix.cpp
  src/scenegraph/MatrixTransform.h
  src/scenegraph/Model.cpp
  src/scenegraph/ModelSkin.cpp
Labels: Optimization
