Repository pioneerspacesim/pioneer, pull requests merged in 2023-08, with the labels that each got.

#5600 changed up and down crosshairs
  data/icons/icons.svg
Labels: Cosmetic or UI

#5605 Use std::string_view for C++ Lang handling
  src/Lang.cpp
  src/Lang.h
  src/LangStrings.inc.h
  src/Pi.cpp
  src/lua/LuaLang.cpp
Labels: Bite-sized, C++ code

#5606 Model Tag improvements, fix GLTF import
  src/Camera.cpp
  src/Camera.h
  src/FixedGuns.cpp
  src/ModelBody.cpp
  src/ModelBody.h
  src/ModelViewer.cpp
  src/ModelViewer.h
  src/Player.cpp
  src/Ship.cpp
  src/ShipCockpit.cpp
  src/ShipCockpit.h
  src/SpaceStation.cpp
  src/SpaceStationType.cpp
  src/pigui/ModelSpinner.cpp
  src/scenegraph/BinaryConverter.cpp
  src/scenegraph/BinaryConverter.h
  src/scenegraph/Group.cpp
  src/scenegraph/Group.h
  src/scenegraph/Loader.cpp
  src/scenegraph/MatrixTransform.cpp
  src/scenegraph/MatrixTransform.h
  src/scenegraph/Model.cpp
  src/scenegraph/Model.h
  src/scenegraph/Node.cpp
  src/scenegraph/Node.h
  src/scenegraph/NodeVisitor.cpp
  src/scenegraph/NodeVisitor.h
  src/scenegraph/SceneGraph.h
  src/scenegraph/Tag.cpp
  src/scenegraph/Tag.h
  src/ship/CameraController.cpp
Labels: Model system, C++ code

#5607 Re-architect System Map to operate on Object Tracks
  src/SystemView.cpp
  src/SystemView.h
  src/enum_table.cpp
  src/lua/LuaSystemView.cpp
Labels: C++ code

#5610 Disable runtime floating point exceptions
  src/Pi.cpp
  src/ship/PlayerShipController.cpp
  src/ship/ShipController.cpp
Labels: Crash or hang, Upstream issue, C++ code

#5611 Editor Binary and Prerequisites
  CMakeLists.txt
  Modelviewer.txt
  scripts/build-travis.sh
  src/Pi.cpp
  src/Pi.h
  src/core/Application.cpp
  src/core/Application.h
  src/core/GuiApplication.cpp
  src/core/GuiApplication.h
  src/editor/CMakeLists.txt
  src/editor/EditorApp.cpp
  src/editor/EditorApp.h
  src/editor/EditorDraw.cpp
  src/editor/EditorDraw.h
  src/editor/EditorWindow.cpp
  src/editor/EditorWindow.h
  src/editor/ModelViewer.cpp
  src/editor/ModelViewer.h
  src/editor/UndoStepType.h
  src/editor/UndoSystem.cpp
  src/editor/UndoSystem.h
  src/editor/ViewportWindow.cpp
  src/editor/ViewportWindow.h
  src/editor/editormain.cpp
  src/lua/LuaUtils.h
  src/lua/core/Sandbox.cpp
  src/main.cpp
Labels: New feature, C++ code, Tools

#5614 Fix docking location tags in Space Station models
  data/models/stations/ground_station/starport_docking.dae
  data/models/stations/new_ground/landPad6_docking.dae
  data/models/stations/orbital_station/station_B_coll.dae
  data/models/stations/orbital_station/station_docking_A.dae
  data/models/stations/orbital_station/station_docking_B.dae
  data/models/stations/orbital_station/station_hub_A_coll.dae
  src/SpaceStation.cpp
  src/SpaceStationType.cpp
  src/scenegraph/Loader.cpp
Labels: Bug fix, Model system
