Repository pioneerspacesim/pioneer, pull requests merged in 2023-01, with the labels that each got.

#5472 Equipment Balance and tweaks
  data/libs/Equipment.lua
  data/ships/sinonatrix.json
  src/Missile.cpp
  src/Missile.h
Labels: Design

#5475 Font Consistency and Other Bit-Twiddling
  data/pigui/libs/buttons.lua
  data/pigui/libs/commodity-market.lua
  data/pigui/libs/face.lua
  data/pigui/libs/ship-equipment.lua
  data/pigui/libs/text-table.lua
  data/pigui/libs/text.lua
  data/pigui/modules/comms.lua
  data/pigui/modules/info-view/02-personal-info.lua
  data/pigui/modules/info-view/03-econ-trade.lua
  data/pigui/modules/info-view/04-missions.lua
  data/pigui/modules/info-view/05-crew.lua
  data/pigui/modules/info-view/06-flightlog.lua
  data/pigui/modules/sidebar/cargo.lua
  data/pigui/modules/station-view/01-lobby.lua
  data/pigui/modules/station-view/02-bulletinBoard.lua
  data/pigui/modules/station-view/03-commodityMarket.lua
  data/pigui/modules/station-view/04-shipMarket.lua
  data/pigui/modules/station-view/06-shipRepairs.lua
  data/pigui/modules/station-view/07-police.lua
  data/pigui/views/game.lua
  src/lua/LuaPiGui.cpp
Labels: Cosmetic or UI, Bite-sized

#5477 Joystick Configuration and Fixes
  data/lang/input-core/en.json
  data/libs/bind-manager.lua
  data/pigui/libs/forwarded.lua
  data/pigui/modules/settings-window.lua
  data/pigui/themes/default.lua
  src/Input.cpp
  src/Input.h
  src/lua/LuaInput.cpp
  src/lua/LuaPiGui.cpp
  src/ship/PlayerShipController.cpp
  src/ship/PlayerShipController.h
Labels: Cosmetic or UI, Input

#5480 More crash fixes!
  data/pigui/modules/saveloadgame.lua
  src/FileSystem.cpp
  src/Input.h
  src/Pi.cpp
  src/Pi.h
  src/lua/LuaDev.cpp
  src/lua/LuaTimer.cpp
Labels: Crash or hang, Bug fix, Bite-sized

#5483 Fixing the shading of Vlastan Library building
  data/models/buildings/vlastan/LibraryHQ.obj
  data/models/buildings/vlastan/LibraryMQ.obj
Labels: Cosmetic or UI, Art

#5486 Adding gun tag to Lodos
  data/models/ships/lodos/lodos-hi.dae
Labels: Bug fix, Art

#5488 Fix station pads being assigned wrong bay indicies
  src/SpaceStationType.cpp
Labels: Bug fix, C++ code

#5474 Dynamic Station Economies
  data/economy/commodities/high_tech.json
  data/economy/commodities/industrial.json
  data/lang/ui-core/en.json
  data/libs/Economy.lua
  data/libs/SpaceStation.lua
  data/libs/utils.lua
  data/meta/SystemBody.lua
  data/modules/Debug/DebugCommodityPrices.lua
  data/modules/NewsEventCommodity/NewsEventCommodity.lua
  data/pigui/libs/commodity-market.lua
  data/pigui/modules/flight-ui/system-overview.lua
  data/pigui/modules/system-econ-view.lua
  data/pigui/modules/system-overview-window.lua
  data/pigui/modules/system-view-ui.lua
  data/pigui/views/mainmenu.lua
  data/pigui/views/map-sector-view.lua
  src/galaxy/StarSystemGenerator.cpp
  src/galaxy/SystemBody.h
  src/lua/LuaEconomy.cpp
  src/lua/LuaPiGui.cpp
  src/lua/LuaStarSystem.cpp
  src/lua/LuaSystemBody.cpp
Labels: Design, New feature, Savegame bump

#5495 Fix uninitialized variables, memory leaks
  src/FileSystem.h
  src/GasGiantJobs.h
  src/collider/GeomTree.cpp
  src/lua/LuaRef.cpp
  src/lua/LuaRef.h
  src/scenegraph/Model.cpp
  src/ship/ShipViewController.cpp
  src/text/DistanceFieldFont.cpp
  src/text/DistanceFieldFont.h
  src/utils.h
Labels: Bug fix, C++ code

#5498 Fixes, bowfin update, terrain rendering fixes
  data/libs/Economy.lua
  data/libs/FlightLog.lua
  data/modules/AutoSave/AutoSave.lua
  data/modules/Scout/ScanManager.lua
  data/pigui/modules/autopilot-window.lua
  data/pigui/modules/ship-internals-window.lua
  data/pigui/modules/station-view/01-lobby.lua
  data/pigui/modules/system-view-ui.lua
  data/ships/bowfin.json
  src/GeoPatch.cpp
  src/GeoPatch.h
  src/GeoPatchJobs.h
Labels: Cosmetic or UI, Bug fix, Lua code, C++ code
