Repository pioneerspacesim/pioneer, pull requests merged in 2023-11, with the labels that each got.

#5663 Lua Constant autocomplete support
  data/meta/Constants.lua
  scripts/scan_enums.py
  src/enum_table.cpp
Labels: Tools

#5643 Fixes and changes for functions in LuaBody/Player/Ship
  data/libs/Ship.lua
  data/meta/CoreObject/Body.meta.lua
  src/Body.cpp
  src/Body.h
  src/enum_table.cpp
  src/enum_table.h
  src/lua/LuaBody.cpp
  src/lua/LuaPlayer.cpp
  src/lua/LuaShip.cpp
Labels: Cosmetic or UI, Bug fix

#5661 Improve Simplex Noise Performance
  src/perlin.cpp
Labels: Optimization

#5651 Build with SSE4 / AVX, fix build artifact generation
  .github/actions/upload-linux/action.yml
  .github/workflows/build-ci.yml
  CMakeLists.txt
  scripts/CMakeBuildPresetsCI.json
  scripts/build-release.sh
  scripts/package-release.sh
Labels: Build, Optimization

#5670 Improve CI Setup and Performance
  .github/workflows/build-ci.yml
  .github/workflows/clang-format.yml
  CMakePresets.json
  src/editor/ModelViewerWidget.cpp
  src/editor/ModelViewerWidget.h
Labels: Build

#5669 Improve BVH Broadphase Performance
  src/Aabb.h
  src/Frame.cpp
  src/Frame.h
  src/collider/BVHTree.cpp
  src/collider/BVHTree.h
  src/collider/CollisionSpace.cpp
  src/collider/CollisionSpace.h
  src/collider/Geom.cpp
  src/collider/Geom.h
  src/core/macros.h
  src/graphics/Drawables.cpp
  src/graphics/Drawables.h
  src/scenegraph/Model.cpp
  src/vector3.h
Labels: Optimization, C++ code

#5657 Fix lua components corruption on save
  src/Space.cpp
  src/lua/LuaSerializer.cpp
Labels: Savegame bump
