Repository pioneerspacesim/pioneer, pull requests merged in 2023-10, with the labels that each got.

#5609 Fuel scooping rework
  data/modules/FuelScoop.lua
  src/Ship.cpp
  src/Ship.h
Labels: Design

#5631 Fix for glued cockpit
  src/ShipCockpit.cpp
Labels: Cosmetic or UI, Bug fix

#5634 Search bar for save/load window and crashes fix
  data/lang/ui-core/ar.json
  data/lang/ui-core/bg.json
  data/lang/ui-core/ca.json
  data/lang/ui-core/cs.json
  data/lang/ui-core/da.json
  data/lang/ui-core/de.json
  data/lang/ui-core/el.json
  data/lang/ui-core/en.json
  data/lang/ui-core/eo.json
  data/lang/ui-core/es.json
  data/lang/ui-core/fr.json
  data/lang/ui-core/ga.json
  data/lang/ui-core/gd.json
  data/lang/ui-core/hr.json
  data/lang/ui-core/hu.json
  data/lang/ui-core/id.json
  data/lang/ui-core/it.json
  data/lang/ui-core/ja-Hira.json
  data/lang/ui-core/ja.json
  data/lang/ui-core/ja_JP.json
  data/lang/ui-core/lt.json
  data/lang/ui-core/nb.json
  data/lang/ui-core/nl.json
  data/lang/ui-core/pl.json
  data/lang/ui-core/pt.json
  data/lang/ui-core/pt_BR.json
  data/lang/ui-core/ro.json
  data/lang/ui-core/ru.json
  data/lang/ui-core/sv.json
  data/lang/ui-core/tr.json
  data/lang/ui-core/zh.json
  data/modules/Debug/DebugCommodityPrices.lua
  data/pigui/libs/forwarded.lua
  data/pigui/modules/new-game-window/ship.lua
  data/pigui/modules/saveloadgame.lua
  src/lua/LuaPiGui.cpp
Labels: Cosmetic or UI

#5632 Compare specs of your current ship to those in the ship market and highlight changes
  data/lang/ui-core/en.json
  data/pigui/libs/text.lua
  data/pigui/modules/station-view/04-shipMarket.lua
  data/pigui/themes/default.lua
Labels: Cosmetic or UI

#5622 Improve random system generation, load custom systems from JSON
  data/systems/00_sol.lua
  data/systems/01_epsilon_eridani.lua
  data/systems/02_local_stars.lua
  data/systems/custom/00_sol.json
  data/systems/partial/02_local_stars.json
  src/CityOnPlanet.cpp
  src/FileSystem.h
  src/JsonUtils.cpp
  src/JsonUtils.h
  src/Planet.cpp
  src/Random.h
  src/core/Log.h
  src/galaxy/CustomSystem.cpp
  src/galaxy/CustomSystem.h
  src/galaxy/Factions.cpp
  src/galaxy/GalaxyGenerator.cpp
  src/galaxy/NameGenerator.cpp
  src/galaxy/NameGenerator.h
  src/galaxy/SectorGenerator.cpp
  src/galaxy/StarSystem.cpp
  src/galaxy/StarSystem.h
  src/galaxy/StarSystemGenerator.cpp
  src/galaxy/StarSystemGenerator.h
  src/galaxy/SystemBody.cpp
  src/galaxy/SystemBody.h
  src/gameconsts.h
  src/lua/LuaSystemBody.cpp
  src/pigui/PerfInfo.cpp
Labels: Design, New feature, Savegame bump, C++ code, Tools

#5592 Planet density
  data/lang/core/en.json
  data/lang/module-advice/en.json
  data/lang/module-searchrescue/en.json
  data/modules/Advice/Advice.lua
  data/modules/SearchRescue/SearchRescue.lua
  data/pigui/modules/system-view-ui.lua
  src/LangStrings.inc.h
  src/galaxy/StarSystemGenerator.cpp
  src/galaxy/SystemBody.cpp
  src/galaxy/SystemBody.h
  src/lua/LuaSystemBody.cpp
Labels: Savegame bump

#5641 Wording change for commands in the "Crew Roster" window
  data/pigui/modules/info-view/05-crew.lua
Labels: Cosmetic or UI

#5645 Fix main menu music not starting to play after exiting back to main menu
  data/pigui/views/mainmenu.lua
Labels: Cosmetic or UI, Bug fix

#5642 Disable scrolling for tab-view and character info
  data/pigui/libs/face.lua
  data/pigui/views/tab-view.lua
Labels: Cosmetic or UI

#5625 System Editor
  data/systems/custom/00_sol.json
  src/SystemView.cpp
  src/editor/ActionBinder.cpp
  src/editor/ActionBinder.h
  src/editor/CMakeLists.txt
  src/editor/EditorApp.cpp
  src/editor/EditorApp.h
  src/editor/EditorDraw.cpp
  src/editor/EditorDraw.h
  src/editor/EditorIcons.h
  src/editor/EditorWindow.cpp
  src/editor/Modal.cpp
  src/editor/Modal.h
  src/editor/ModelViewer.cpp
  src/editor/ModelViewerWidget.cpp
  src/editor/UndoStepType.h
  src/editor/UndoSystem.cpp
  src/editor/UndoSystem.h
  src/editor/ViewportWindow.cpp
  src/editor/system/GalaxyEditAPI.cpp
  src/editor/system/GalaxyEditAPI.h
  src/editor/system/SystemBodyUndo.h
  src/editor/system/SystemEditor.cpp
  src/editor/system/SystemEditor.h
  src/editor/system/SystemEditorHelpers.cpp
  src/editor/system/SystemEditorHelpers.h
  src/editor/system/SystemEditorModals.cpp
  src/editor/system/SystemEditorModals.h
  src/editor/system/SystemEditorViewport.cpp
  src/editor/system/SystemEditorViewport.h
  src/galaxy/StarSystem.h
  src/galaxy/StarSystemGenerator.cpp
  src/galaxy/StarSystemGenerator.h
  src/galaxy/SystemBody.cpp
  src/graphics/Renderer.h
  src/graphics/dummy/RendererDummy.h
  src/graphics/opengl/RendererGL.cpp
  src/graphics/opengl/RendererGL.h
  src/lua/LuaEngine.cpp
  src/pigui/PiGuiRenderer.cpp
  src/terrain/Terrain.cpp
Labels: New feature, Savegame bump, C++ code, Tools
