Repository pioneerspacesim/pioneer, pull requests merged in 2024-06, with the labels that each got.

#5835 Removing stray triangles from Bluenose
  data/models/ships/bluenose/bluenose_hi.dae
Labels: Cosmetic or UI, Cleanup, Art, Bite-sized

#5843 Fix mission list error when opened during hyperspace
  data/meta/CoreObject/Player.meta.lua
  data/pigui/modules/info-view/04-missions.lua
Labels: Bug fix

#5842 Fix lots of missing ship labels
  data/libs/SpaceStation.lua
  data/modules/SearchRescue/SearchRescue.lua
  data/pigui/modules/new-game-window/class.lua
  data/pigui/modules/new-game-window/crew.lua
  data/pigui/modules/new-game-window/ship.lua
  data/pigui/modules/new-game-window/widgets.lua
  data/pigui/modules/station-view/06-shipRepairs.lua
  src/scenegraph/Label3D.cpp
Labels: Cosmetic or UI, Bug fix

#5841 Improve surface scan missions on high-pressure worlds
  data/lang/module-scout/en.json
  data/modules/Scout/Scout.lua
Labels: Cosmetic or UI, Bug fix

#5846 Sort commodity names by translated string
  data/pigui/modules/system-econ-view.lua
Labels: Cosmetic or UI, Bug fix, Bite-sized

#5847 Fix malformed Exec key in installed .desktop file
  CMakeLists.txt
  cmake/InstallPioneer.cmake
Labels: Bug fix, Build
