Repository pioneerspacesim/pioneer, pull requests merged in 2024-11, with the labels that each got.

#5949 feat: degrade scooped cargo requiring cargo life support
  data/modules/LifeSupport.lua
Labels: New feature

#5948 Improvement: Radar auto-zoom on cargo cannisters
  data/pigui/modules/radar.lua
Labels: Cosmetic or UI

#5943 Optimize CityOnPlanet CPU-side rendering cost
  CMakeLists.txt
  src/Camera.cpp
  src/Camera.h
  src/CityOnPlanet.cpp
  src/CityOnPlanet.h
  src/GeoPatch.cpp
  src/GeoPatch.h
  src/Plane.cpp
  src/Plane.h
  src/SpaceStation.cpp
  src/WorldView.cpp
  src/graphics/Frustum.cpp
  src/graphics/Frustum.h
  src/graphics/Graphics.cpp
  src/graphics/Graphics.h
  src/math/Plane.h
  src/math/Sphere.cpp
  src/math/Sphere.h
  src/pigui/ModelSpinner.cpp
  src/scenegraph/Group.cpp
  src/scenegraph/Group.h
  src/scenegraph/LOD.cpp
  src/scenegraph/LOD.h
  src/scenegraph/MatrixTransform.cpp
  src/scenegraph/MatrixTransform.h
  src/scenegraph/Model.cpp
  src/scenegraph/Model.h
  src/scenegraph/ModelNode.cpp
  src/scenegraph/ModelNode.h
  src/scenegraph/Node.h
  src/scenegraph/StaticGeometry.cpp
  src/scenegraph/StaticGeometry.h
Labels: Performance, C++ code, Rendering

#5945 Add Buy and Sell prices to the Commodity Market
  data/lang/ui-core/en.json
  data/pigui/libs/commodity-market.lua
Labels: Cosmetic or UI

#5964 Removing normal map from default cockpit materials
  data/models/cockpits/default_cockpit/default_cockpit.model
Labels: Cosmetic or UI, Bug fix, Art, Bite-sized

#5965 Fully expose InputBindings to Lua
  data/meta/Input.lua
  data/modules/Debug/TestInput.lua
  data/pigui/libs/forwarded.lua
  data/pigui/modules/autopilot-window.lua
  src/Input.cpp
  src/Input.h
  src/lua/Lua.cpp
  src/lua/LuaInput.cpp
  src/lua/LuaInput.h
  src/lua/LuaPiGui.cpp
  src/lua/LuaUtils.h
  src/lua/core/Import.cpp
  src/pigui/LuaPiGui.cpp
  src/pigui/LuaPiGui.h
  src/pigui/PiGuiSandbox.cpp
Labels: New feature, Input, Lua API

#5962 feat(ui): add keybinding for target radial
  data/pigui/libs/radial-menu.lua
  data/pigui/modules/flight-ui/reticule.lua
  src/WorldView.cpp
Labels: Cosmetic or UI, Bite-sized

#5967 Linux de-profile and msvc compilation fix
  CMakePresets.json
  contrib/profiler/Profiler.cpp
  src/Frame.cpp
Labels: C++ code

#5958 feat(radar): add manual zoom mode to scanner
  data/fonts/UIFont.json
  data/fonts/UIHeadingFont.json
  data/fonts/UIIconFont.json
  data/fonts/UIMonoFont.json
  data/icons/icons.svg
  data/lang/input-core/en.json
  data/lang/ui-core/en.json
  data/pigui/libs/icons.lua
  data/pigui/modules/autopilot-window.lua
  data/pigui/modules/radar.lua
  data/pigui/modules/ship-internals-window.lua
  data/pigui/themes/default.lua
  src/Pi.cpp
  src/pigui/Radar.cpp
Labels: Cosmetic or UI, Lua code

#5970 Allocate light data UBO from per-frame allocator, misc. fixes and cleanup
  CMakeLists.txt
  contrib/profiler/Profiler.cpp
  data/pigui/modules/station-view/04-shipMarket.lua
  src/graphics/opengl/MaterialGL.cpp
  src/graphics/opengl/RendererGL.cpp
  src/graphics/opengl/RendererGL.h
  src/graphics/opengl/UniformBuffer.cpp
  src/graphics/opengl/UniformBuffer.h
  src/graphics/opengl/VertexBufferGL.cpp
  src/scenegraph/StaticGeometry.cpp
Labels: Bug fix, Cleanup

#5982 Fixing icons.svg after the radar updates
  data/icons/icons.svg
Labels: Cosmetic or UI, Bug fix, Art

#5975 Natrix patterns
  data/models/ships/natrix/natrix.model
  data/models/ships/natrix/pattern_01.dds
  data/models/ships/natrix/pattern_02.dds
  data/models/ships/natrix/pattern_03.dds
  data/models/ships/natrix/pattern_04.dds
  data/models/ships/natrix/pattern_05.dds
  data/models/ships/natrix/pattern_06.dds
  data/models/ships/natrix/pattern_07.dds
  data/models/ships/natrix/pattern_08.dds
  data/models/ships/natrix/pattern_09.dds
Labels: Art

#5978 feat(radar): capture mouse wheel for zooming radar
  data/pigui/modules/radar.lua
Labels: Cosmetic or UI, Input

#5984 Feat/radar improvements
  data/pigui/modules/radar.lua
  src/sound/SoundMusic.cpp
Labels: Cosmetic or UI, New feature, Cleanup

#5988 fix(flightlog): fix crash when removing a flight log entry
  data/pigui/modules/info-view/06-flightlog.lua
Labels: Bug fix, Bite-sized, Lua code

#5990 Updating Vatakara to use the shild mesh of the Malabar
  data/ships/vatakara.json
Labels: Bug fix, Art, Bite-sized
