Repository pioneerspacesim/pioneer, pull requests merged in 2024-02, with the labels that each got.

#5729 Microfixes
  .github/actions/upload-linux/action.yml
  .github/workflows/build-ci.yml
  .github/workflows/clang-format.yml
  .github/workflows/naturaldocs.yml
  CMakePresets.json
  COMPILING.txt
  src/Game.cpp
  src/editor/EditorApp.cpp
  src/editor/EditorApp.h
  src/lua/LuaBody.cpp
Labels: Bug fix

#5737 Adding editor.txt
  Modelviewer.txt
  editor.txt
Labels: Bite-sized, Tools

#5759 Update libfmt, fix compilation warnings and invalid JSON CustomSystem position
  CMakeLists.txt
  contrib/fmt/CMakeLists.txt
  contrib/fmt/LICENSE
  contrib/fmt/include/fmt/args.h
  contrib/fmt/include/fmt/chrono.h
  contrib/fmt/include/fmt/color.h
  contrib/fmt/include/fmt/compile.h
  contrib/fmt/include/fmt/core.h
  contrib/fmt/include/fmt/format-inl.h
  contrib/fmt/include/fmt/format.h
  contrib/fmt/include/fmt/locale.h
  contrib/fmt/include/fmt/os.h
  contrib/fmt/include/fmt/ostream.h
  contrib/fmt/include/fmt/posix.h
  contrib/fmt/include/fmt/printf.h
  contrib/fmt/include/fmt/ranges.h
  contrib/fmt/include/fmt/std.h
  contrib/fmt/include/fmt/xchar.h
  contrib/fmt/src/fmt.cc
  contrib/fmt/src/format.cc
  contrib/fmt/src/os.cc
  contrib/fmt/support/cmake/JoinPaths.cmake
  contrib/fmt/support/cmake/cxx14.cmake
  contrib/fmt/support/cmake/fmt-config.cmake.in
  contrib/fmt/support/cmake/fmt.pc.in
  contrib/vcacheopt/vcacheopt.h
  src/Background.cpp
  src/CityOnPlanet.cpp
  src/Input.cpp
  src/Input.h
  src/InputBindings.cpp
  src/core/Application.cpp
  src/core/Log.cpp
  src/core/Log.h
  src/editor/UndoStepType.h
  src/editor/UndoSystem.h
  src/editor/system/GalaxyEditAPI.cpp
  src/editor/system/SystemEditor.cpp
  src/editor/system/SystemEditorHelpers.cpp
  src/editor/system/SystemEditorViewport.cpp
  src/galaxy/CustomSystem.cpp
  src/galaxy/StarSystem.cpp
  src/galaxy/StarSystemGenerator.cpp
  src/graphics/opengl/OpenGLLibs.h
  src/graphics/opengl/Program.cpp
  src/graphics/opengl/RendererGL.cpp
  src/lua/LuaPiGui.cpp
  src/lua/LuaPlayer.cpp
  src/test/TestLuaPushPull.cpp
  src/versioningInfo.cpp
Labels: C++ code

#5756 Local missions should list distances in AU rather than Ly
  data/pigui/modules/info-view/04-missions.lua
Labels: Cosmetic or UI

#5766 Generate atmospheres for gas giants in legacy custom systems
  src/galaxy/CustomSystem.cpp
Labels: Bug fix

#5772 Editor Welcome Screen
  src/editor/EditorApp.cpp
  src/editor/EditorApp.h
  src/editor/EditorIcons.h
  src/editor/system/SystemEditor.cpp
Labels: Tools

#5773 Misc cleanup, fixes, and Lua function library improvements
  data/lang/core/en.json
  data/libs/SpaceStation.lua
  data/libs/autoload.lua
  data/libs/utils.lua
  data/meta/Color.lua
  data/meta/Rand.lua
  data/pigui/baseui.lua
  data/pigui/init.lua
  data/pigui/libs/buttons.lua
  data/pigui/libs/commodity-market.lua
  data/pigui/libs/forwarded.lua
  data/pigui/libs/gauge.lua
  data/pigui/libs/icons.lua
  data/pigui/libs/text.lua
  data/pigui/libs/wrappers.lua
  data/pigui/modules/station-view/04-shipMarket.lua
  data/pigui/themes/default.lua
  data/pigui/views/tab-view.lua
  src/Player.cpp
  src/Player.h
  src/lua/LuaPiGui.cpp
Labels: Bug fix, Lua API

#5780 A few spelling / grammar fixes
  data/lang/core/en.json
  data/lang/module-deliverpackage/en.json
  data/lang/module-goodstrader/en.json
  data/lang/module-newseventcommodity/en.json
  data/lang/module-policepatrol/en.json
  data/lang/module-scout/en.json
  data/lang/module-searchrescue/en.json
  data/lang/module-taxi/en.json
  data/lang/ui-core/en.json
Labels: Cleanup

#5781 Update Github Upload-Artifact action for Windows CI
  .github/workflows/build-ci.yml
Labels: Bite-sized

#5779 Resizable Editor Window
  src/Camera.cpp
  src/DeathView.cpp
  src/Input.cpp
  src/Intro.cpp
  src/ObjectViewerView.cpp
  src/Pi.cpp
  src/SectorMap.cpp
  src/Sfx.cpp
  src/ShipAICmd.cpp
  src/WorldView.cpp
  src/core/GuiApplication.cpp
  src/core/GuiApplication.h
  src/editor/EditorApp.cpp
  src/editor/system/SystemEditor.cpp
  src/editor/system/SystemEditor.h
  src/graphics/Graphics.cpp
  src/graphics/Graphics.h
  src/graphics/RenderTarget.h
  src/graphics/Renderer.h
  src/graphics/opengl/RendererGL.cpp
  src/graphics/opengl/RendererGL.h
  src/lua/LuaConsole.cpp
  src/lua/LuaPiGui.cpp
  src/lua/LuaSystemView.cpp
  src/scenegraph/Billboard.cpp
  src/scenegraph/LOD.cpp
Labels: New feature, Tools, Rendering

#5785 Adding landing spike to Mola Ramsayi collision mesh
  data/models/ships/molaramsayi/molaramsayi_col.dae
Labels: Bug fix, Art, Bite-sized
