Repository pioneerspacesim/pioneer, pull requests merged in 2024-01, with the labels that each got.

#5671 Refactor Event Queues
  data/libs/Event.lua
  data/libs/autoload.lua
  data/meta/_Core.lua
  data/pigui/baseui.lua
  src/Game.cpp
  src/Pi.cpp
  src/Ship.cpp
  src/lua/Lua.cpp
  src/lua/LuaEvent.cpp
  src/lua/LuaEvent.h
  src/lua/LuaPiGui.cpp
  src/lua/LuaPushPull.h
  src/lua/LuaTable.h
  src/lua/core/Import.cpp
  src/pigui/LuaPiGui.cpp
  src/pigui/LuaPiGui.h
Labels: C++ code, Lua API

#5692 Avoid misaligned read when loading SGM files
  src/scenegraph/Serializer.h
Labels: Bug fix, Platform Specific

#5637 Add Space.GetBodiesNear(), ProximityQuery module
  data/libs/SpaceStation.lua
  data/meta/Space.lua
  data/modules/Assassination/Assassination.lua
  data/modules/BulkShips.lua
  data/modules/Common/ProximityQuery.lua
  data/modules/SearchRescue/SearchRescue.lua
  data/modules/System/Explore.lua
  data/modules/TradeShips/Debug.lua
  data/modules/TradeShips/Flow.lua
  src/lua/LuaBody.cpp
  src/lua/LuaBody.h
  src/lua/LuaPiGui.cpp
  src/lua/LuaSpace.cpp
  src/pigui/LuaFlags.h
Labels: Feature request, Optimization, Bite-sized

#5674 Delete button for saveloadwindow, make this window less error prone (and some more)
  data/lang/core/en.json
  data/lang/ui-core/en.json
  data/meta/CoreObject/Game.meta.lua
  data/pigui/libs/forwarded.lua
  data/pigui/libs/message-box.lua
  data/pigui/libs/ui-timer.lua
  data/pigui/modules/saveloadgame.lua
  data/pigui/views/game.lua
  data/pigui/views/mainmenu.lua
  src/FileSystem.h
  src/Game.cpp
  src/Game.h
  src/LangStrings.inc.h
  src/lua/LuaGame.cpp
  src/lua/LuaPiGui.cpp
  src/posix/FileSystemPosix.cpp
  src/win32/FileSystemWin32.cpp
Labels: Cosmetic or UI

#5540 System overview icon upscale and update
  AUTHORS.txt
  data/icons/object_brown_dwarf.png
  data/icons/object_planet_asteroid.png
  data/icons/object_planet_co2.png
  data/icons/object_planet_co2_2.png
  data/icons/object_planet_co2_3.png
  data/icons/object_planet_co2_4.png
  data/icons/object_planet_desert.png
  data/icons/object_planet_desert2.png
  data/icons/object_planet_dwarf.png
  data/icons/object_planet_ice.png
  data/icons/object_planet_ice2.png
  data/icons/object_planet_large_gas_giant.png
  data/icons/object_planet_large_gas_giant_hot.png
  data/icons/object_planet_life.png
  data/icons/object_planet_life2.png
  data/icons/object_planet_life3.png
  data/icons/object_planet_life4.png
  data/icons/object_planet_life5.png
  data/icons/object_planet_life6.png
  data/icons/object_planet_life7.png
  data/icons/object_planet_life8.png
  data/icons/object_planet_medium_gas_giant.png
  data/icons/object_planet_medium_gas_giant_hot.png
  data/icons/object_planet_methane.png
  data/icons/object_planet_methane2.png
  data/icons/object_planet_methane3.png
  data/icons/object_planet_small.png
  data/icons/object_planet_small_gas_giant.png
  data/icons/object_planet_small_gas_giant_hot.png
  data/icons/object_planet_volcanic.png
  data/icons/object_planet_water.png
  data/icons/object_planet_water2.png
  data/icons/object_planet_water3.png
Labels: Cosmetic or UI, Art

#5715 Making ship market comparison colors colorblind friendly
  data/pigui/themes/default.lua
Labels: Cosmetic or UI, Accessibility

#5708 improve planet rings shaders
  data/shaders/opengl/lib.glsl
  data/shaders/opengl/planetrings.frag
  data/shaders/opengl/planetrings.vert
  src/Planet.cpp
Labels: Rendering

#5720 Fix player being unable to collide with Stations if only ship in Frame
  src/collider/BVHTree.cpp
  src/collider/CollisionSpace.cpp
Labels: Bug fix, C++ code

#5617 realistic Rayleigh/Mie atmospheric scattering
  data/lang/ui-core/en.json
  data/pigui/modules/settings-window.lua
  data/shaders/opengl/basesphere_uniforms.glsl
  data/shaders/opengl/gassphere_base.frag
  data/shaders/opengl/geosphere_sky.frag
  data/shaders/opengl/geosphere_terrain.frag
  data/shaders/opengl/geosphere_terrain.vert
  data/shaders/opengl/lib.glsl
  data/shaders/opengl/planetrings.frag
  data/shaders/opengl/rayleigh.glsl
  data/shaders/opengl/rayleigh_accurate.frag
  data/shaders/opengl/rayleigh_accurate.shaderdef
  data/shaders/opengl/rayleigh_accurate.vert
  data/shaders/opengl/rayleigh_fast.frag
  data/shaders/opengl/rayleigh_fast.shaderdef
  data/shaders/opengl/rayleigh_fast.vert
  data/shaders/opengl/sRGB.glsl
  src/BaseSphere.cpp
  src/Camera.cpp
  src/GasGiant.cpp
  src/GeoSphere.cpp
  src/GeoSphere.h
  src/SectorMap.cpp
  src/galaxy/AtmosphereParameters.h
  src/galaxy/SystemBody.cpp
  src/galaxy/SystemBody.h
  src/graphics/Drawables.cpp
  src/graphics/Drawables.h
  src/lua/LuaEngine.cpp
Labels: Rendering

#5721 Save and load the current planned hyperjump in the save file
  data/pigui/modules/hyperjump-planner.lua
  data/pigui/views/map-sector-view.lua
  src/SectorView.cpp
Labels: Cosmetic or UI, Bug fix, Savegame bump

#5728 Fix missing gas giant atmospheres
  data/libs/Equipment.lua
  data/meta/SystemBody.lua
  data/modules/Scout/Scout.lua
  data/systems/custom/00_sol.json
  src/editor/system/GalaxyEditAPI.cpp
  src/galaxy/StarSystemGenerator.cpp
  src/lua/LuaSystemBody.cpp
Labels: Bug fix, Lua API
