Repository pioneerspacesim/pioneer, pull requests merged in 2024-10, with the labels that each got.

#5906 NameGen - Spice up the station names
  data/libs/NameGen.lua
Labels: Savegame bump

#5789 Improve narrow-phase collision physics performance
  src/Aabb.h
  src/collider/BVHTree.cpp
  src/collider/BVHTree.h
  src/collider/CollisionContact.h
  src/collider/CollisionSpace.cpp
  src/collider/Geom.cpp
  src/collider/Geom.h
  src/collider/GeomTree.cpp
  src/collider/GeomTree.h
  src/editor/ModelViewer.cpp
  src/editor/ModelViewer.h
  src/graphics/opengl/RendererGL.cpp
Labels: Performance

#5922 Feat/reset view on hyperspace exit
  CMakeLists.txt
  data/lang/ui-core/en.json
  data/libs/Player.lua
  data/meta/Constants.lua
  data/pigui/modules/settings-window.lua
  data/pigui/modules/system-view-ui.lua
  data/pigui/views/map-sector-view.lua
  src/Player.cpp
  src/SectorView.cpp
  src/SystemView.cpp
  src/SystemView.h
  src/enum_table.cpp
  src/enum_table.h
  src/lua/LuaEngine.cpp
  src/lua/LuaSystemView.cpp
Labels: Cosmetic or UI

#5931 CppCheck 2.15 performance cleanup
  scripts/Pioneer.cppcheck
  src/Background.cpp
  src/BaseSphere.cpp
  src/FileSystem.cpp
  src/FileSystem.h
  src/GasGiant.cpp
  src/GasGiant.h
  src/GeoSphere.cpp
  src/GeoSphere.h
  src/HudTrail.cpp
  src/Input.cpp
  src/Input.h
  src/Intro.cpp
  src/ObjectViewerView.cpp
  src/Pi.cpp
  src/RefCounted.h
  src/SectorView.cpp
  src/SectorView.h
  src/Space.cpp
  src/SystemView.cpp
  src/SystemView.h
  src/collider/GeomTree.cpp
  src/collider/GeomTree.h
  src/core/GuiApplication.cpp
  src/core/GuiApplication.h
  src/core/Log.cpp
  src/core/Log.h
  src/core/StringUtils.cpp
  src/editor/ActionBinder.cpp
  src/editor/ActionBinder.h
  src/galaxy/GalaxyGenerator.h
  src/galaxy/StarSystem.h
  src/galaxy/SystemPath.cpp
  src/graphics/Drawables.cpp
  src/graphics/Frustum.cpp
  src/graphics/Frustum.h
  src/graphics/ShaderParser.cpp
  src/graphics/ShaderParser.h
  src/graphics/VertexArray.cpp
  src/lua/LuaInput.cpp
  src/lua/LuaMusic.cpp
  src/lua/LuaStarSystem.cpp
  src/lua/core/Import.cpp
  src/pigui/LuaPiGui.cpp
  src/pigui/LuaPiGui.h
  src/pigui/PiGui.cpp
  src/pigui/PiGuiView.h
  src/scenegraph/Model.h
  src/scenegraph/Serializer.h
  src/sound/Sound.cpp
  src/sound/SoundMusic.cpp
  src/sound/SoundMusic.h
  src/win32/msvc_bug.cpp
Labels: Cleanup, C++ code

#5937 Misc. improvements
  data/lang/core/en.json
  data/libs/Event.lua
  data/libs/autoload.lua
  data/libs/utils.lua
  data/meta/CoreObject/Ship.meta.lua
  data/meta/Engine.lua
  data/meta/Model.lua
  data/modules/MissionUtils.lua
  data/pigui/libs/buttons.lua
  data/pigui/libs/forwarded.lua
  data/pigui/libs/icons.lua
  data/pigui/libs/text.lua
  data/pigui/libs/wrappers.lua
  data/pigui/views/debug.lua
  src/lua/LuaJson.cpp
  src/lua/LuaJson.h
  src/lua/LuaPiGui.cpp
Labels: Bite-sized, Lua code
