Repository pioneerspacesim/pioneer, pull requests merged in 2024-08, with the labels that each got.

#5888 Added Perf-Info button to Dump a system to systemeditor compatible JSON
  src/editor/system/SystemEditor.cpp
  src/pigui/PerfInfo.cpp
Labels: Bite-sized, C++ code

#5871 Don't build against lzcnt by default and enable USE_SSE42 only on Intel architecture
  .github/workflows/build-ci.yml
  CMakeLists.txt
  cmake/TargetArchitecture.cmake
Labels: Build

#5840 Separate shield meshes from ship models
  .clangd
  data/models/ships/coronatrix/coronatrix.model
  data/models/ships/coronatrix/coronatrix_shield.dae
  data/models/ships/coronatrix/coronatrix_shield.model
  data/ships/coronatrix.json
  src/Body.h
  src/ModelBody.cpp
  src/ModelBody.h
  src/ModelCache.cpp
  src/Shields.cpp
  src/Shields.h
  src/Ship.cpp
  src/Ship.h
  src/ShipType.cpp
  src/ShipType.h
  src/editor/ModelViewer.cpp
  src/editor/ModelViewer.h
  src/editor/ModelViewerWidget.cpp
  src/lua/LuaShipDef.cpp
  src/pigui/ModelSpinner.cpp
  src/pigui/ModelSpinner.h
  src/scenegraph/StaticGeometry.cpp
Labels: Model system, Savegame bump, Rendering

#5884 Invert illegal commodities icons in the Economy & Trade view. Fix #5876
  data/pigui/modules/system-econ-view.lua
Labels: Cosmetic or UI, Bug fix

#5865 Implement a consistent (and purple!) UI theme
  data/fonts/UIFont.json
  data/fonts/UIHeadingFont.json
  data/fonts/UIIconFont.json
  data/fonts/UIMonoFont.json
  data/icons/icons.svg
  data/meta/FileSystem.lua
  data/meta/Lang.lua
  data/modules/Scout/ScanDisplay.lua
  data/modules/TradeShips/Debug.lua
  data/pigui/libs/buttons.lua
  data/pigui/libs/face.lua
  data/pigui/libs/forwarded.lua
  data/pigui/libs/icons.lua
  data/pigui/libs/item-card.lua
  data/pigui/libs/sidebar.lua
  data/pigui/libs/table.lua
  data/pigui/libs/wrappers.lua
  data/pigui/modules/autopilot-window.lua
  data/pigui/modules/flight-ui/system-overview.lua
  data/pigui/modules/fx-window.lua
  data/pigui/modules/hyperjump-planner.lua
  data/pigui/modules/info-view/03-econ-trade.lua
  data/pigui/modules/info-view/06-flightlog.lua
  data/pigui/modules/new-game-window/flight-log.lua
  data/pigui/modules/new-game-window/ship.lua
  data/pigui/modules/new-game-window/widgets.lua
  data/pigui/modules/radar.lua
  data/pigui/modules/settings-window.lua
  data/pigui/modules/ship-internals-window.lua
  data/pigui/modules/sidebar/cargo.lua
  data/pigui/modules/station-view/02-bulletinBoard.lua
  data/pigui/modules/station-view/04-shipMarket.lua
  data/pigui/modules/system-econ-view.lua
  data/pigui/modules/system-overview-window.lua
  data/pigui/modules/system-view-ui.lua
  data/pigui/modules/time-window.lua
  data/pigui/themes/default.lua
  data/pigui/views/mainmenu.lua
  data/pigui/views/map-sector-view.lua
  data/pigui/views/tab-view.lua
  src/editor/EditorDraw.cpp
  src/editor/EditorDraw.h
  src/lua/LuaPiGui.cpp
  src/pigui/PiGui.h
  src/pigui/Widgets.cpp
  src/pigui/Widgets.h
Labels: Cosmetic or UI

#5898 Redesign Save/Load window, add UI Notification system
  data/lang/core/en.json
  data/lang/ui-core/en.json
  data/libs/utils.lua
  data/meta/Color.lua
  data/meta/CoreObject/Game.meta.lua
  data/meta/Space.lua
  data/modules/Common/ProximityQuery.lua
  data/modules/FlightLog/FlightLogEntries.lua
  data/modules/FlightLog/FlightLogExporter.lua
  data/pigui/init.lua
  data/pigui/libs/buttons.lua
  data/pigui/libs/forwarded.lua
  data/pigui/libs/modal-win.lua
  data/pigui/libs/module.lua
  data/pigui/libs/notification.lua
  data/pigui/libs/text.lua
  data/pigui/libs/ui-timer.lua
  data/pigui/modules/saveloadgame.lua
  data/pigui/modules/station-view/02-bulletinBoard.lua
  data/pigui/themes/default.lua
  data/shaders/opengl/rayleigh_accurate.frag
  data/shaders/opengl/rayleigh_accurate.shaderdef
  data/shaders/opengl/rayleigh_accurate.vert
  data/shaders/opengl/rayleigh_fast.frag
  data/shaders/opengl/rayleigh_fast.shaderdef
  data/shaders/opengl/rayleigh_fast.vert
  data/shaders/opengl/sRGB.glsl
  src/Game.cpp
  src/Game.h
  src/Ship.h
  src/lua/LuaBody.h
  src/lua/LuaGame.cpp
  src/lua/LuaPiGui.cpp
Labels: Cosmetic or UI, New feature

#5899 Improve PerfInfo debug window
  data/modules/Debug/DebugCommodityPrices.lua
  data/modules/Debug/DebugRPG.lua
  data/modules/Debug/DebugShipSpawn.lua
  data/modules/Debug/DebugShipSpawn.moon
  data/modules/NewsEventCommodity/NewsEventCommodity.lua
  data/modules/TradeShips/Debug.lua
  data/pigui/libs/wrappers.lua
  data/pigui/modules/theme-debug.lua
  data/pigui/views/debug.lua
  src/Pi.cpp
  src/pigui/PerfInfo.cpp
  src/pigui/PerfInfo.h
Labels: Cosmetic or UI, Performance

#5900 Clarify system-level economy display
  data/lang/ui-core/en.json
  data/pigui/modules/system-econ-view.lua
  data/pigui/themes/default.lua
Labels: Cosmetic or UI

#5901 Add ability to reroll random systems to System Editor
  src/editor/EditorWindow.cpp
  src/editor/EditorWindow.h
  src/editor/ViewportWindow.cpp
  src/editor/system/GalaxyEditAPI.cpp
  src/editor/system/SystemEditor.cpp
  src/editor/system/SystemEditor.h
  src/editor/system/SystemEditorHelpers.cpp
  src/editor/system/SystemEditorHelpers.h
  src/editor/system/SystemEditorModals.cpp
  src/editor/system/SystemEditorViewport.cpp
  src/galaxy/StarSystem.h
  src/galaxy/StarSystemGenerator.cpp
Labels: Tools
