Repository pioneerspacesim/pioneer, pull requests merged in 2024-03, with the labels that each got.

#5782 Minor model fixes (Lodos, Coronatrix)
  data/models/ships/coronatrix/coronatrix.model
  data/models/ships/coronatrix/coronatrix_police.model
  data/models/ships/lodos/lodos-hi.dae
Labels: Art

#5774 Add Lua "Persistent Object" Serialization
  data/libs/CommodityType.lua
  data/meta/Serializer.lua
  data/modules/Debug/TestSerialization.lua
  src/Game.cpp
  src/lua/LuaSerializer.cpp
  src/lua/LuaSerializer.h
Labels: Lua API

#5793 Fix incorrect position of starports
  src/JsonUtils.cpp
  src/galaxy/CustomSystem.cpp
Labels: Bug fix, Platform Specific

#5794 Fix invalid binary orbits, hyperjump streaks falling down, negative commodity demand
  data/libs/SpaceStation.lua
  src/Background.cpp
  src/galaxy/StarSystemGenerator.cpp
Labels: Bug fix, Bite-sized

#5796 Adding proper collision mesh
  data/models/ships/natrix/natrix.dae
Labels: Bug fix, Art

#5798 Fix backwards save compatibility with v90 saves
  src/lua/LuaSerializer.cpp
Labels: Bug fix, Bite-sized

#5802 Fix speed limiter button positions
  data/pigui/modules/autopilot-window.lua
Labels: Cosmetic or UI, Bug fix
