Repository pioneerspacesim/pioneer, pull requests merged in 2025-05, with the labels that each got.

#5916 ECM crime - Don't use your ECM near a station
  data/lang/ui-core/en.json
  data/libs/Legal.lua
  data/modules/CrimeTracking/CrimeTracking.lua
  src/Ship.cpp
Labels: New feature

#6058 Formatting fixes
  data/lang/core/en.json
  data/lang/module-cargorun/en.json
  data/pigui/libs/text.lua
  data/pigui/modules/info-view/01-ship-info.lua
  data/pigui/modules/info-view/03-econ-trade.lua
  data/pigui/modules/new-game-window/ship.lua
  data/pigui/modules/station-view/01-lobby.lua
  data/pigui/modules/station-view/04-shipMarket.lua
  data/pigui/modules/system-view-ui.lua
  src/editor/system/GalaxyEditAPI.cpp
Labels: Cosmetic or UI

#6143 Upgrade Imgui to 1.91.9b
  contrib/imgui/LICENSE.txt
  contrib/imgui/backends/imgui_impl_sdl2.cpp
  contrib/imgui/backends/imgui_impl_sdl2.h
  contrib/imgui/imconfig.h
  contrib/imgui/imgui.cpp
  contrib/imgui/imgui.h
  contrib/imgui/imgui_demo.cpp
  contrib/imgui/imgui_draw.cpp
  contrib/imgui/imgui_internal.h
  contrib/imgui/imgui_stdlib.cpp
  contrib/imgui/imgui_stdlib.h
  contrib/imgui/imgui_tables.cpp
  contrib/imgui/imgui_widgets.cpp
  contrib/imgui/imstb_textedit.h
  contrib/imgui/imstb_truetype.h
  contrib/imgui/patches/0001-Patch-use-Pioneer-SDL-cursor.patch
  contrib/imgui/patches/0002-Patch-add-PrimDepth-to-ImDrawCmd.patch
  contrib/imgui/patches/0002_pioneer_stack_recover.patch
  contrib/imgui/patches/0003-Patch-add-MissingGlyphs-mechanism-to-ImFont.patch
  contrib/imgui/patches/0004_pioneer_missing_glyphs.patch
  data/libs/utils.lua
  data/modules/TradeShips/Debug.lua
  data/pigui/libs/face.lua
  data/pigui/libs/forwarded.lua
  data/pigui/libs/message-box.lua
  data/pigui/libs/ship-equipment.lua
  data/pigui/libs/wrappers.lua
  data/pigui/modules/new-game-window/crew.lua
  data/pigui/modules/station-view/01-lobby.lua
  data/pigui/modules/station-view/06-shipRepairs.lua
  data/pigui/modules/station-view/07-police.lua
  data/pigui/modules/system-econ-view.lua
  data/pigui/themes/default.lua
  data/pigui/views/station-view.lua
  src/SectorMap.cpp
  src/editor/ActionBinder.cpp
  src/editor/EditorDraw.h
  src/editor/ModelViewer.cpp
  src/editor/ViewportWindow.cpp
  src/lua/LuaPiGui.cpp
  src/pigui/ModelSpinner.cpp
  src/pigui/PerfInfo.cpp
  src/pigui/PiGui.cpp
  src/pigui/PiGuiSandbox.cpp
  src/pigui/Widgets.cpp
Labels: C++ code

#6146 Adding new icons for sector map and about
  data/icons/icons.svg
  data/pigui/themes/default.lua
Labels: Cosmetic or UI, Art
