Repository pioneerspacesim/pioneer, pull requests merged in 2025-06, with the labels that each got.

#6147 Cleaning up unused icons
  data/icons/icons.svg
  data/pigui/themes/default.lua
Labels: Cosmetic or UI, Cleanup, Art

#6148 Redesign Sector Map interface, allow jumping from Sector Map
  data/lang/core/en.json
  data/lang/ui-core/en.json
  data/meta/StarSystem.lua
  data/pigui/baseui.lua
  data/pigui/libs/forwarded.lua
  data/pigui/libs/sidebar.lua
  data/pigui/libs/style.lua
  data/pigui/modules/hyperjump-planner.lua
  data/pigui/themes/default.lua
  data/pigui/views/map-sector-view.lua
  src/SectorView.cpp
  src/SectorView.h
  src/lua/LuaPiGui.cpp
  src/lua/LuaSectorView.cpp
Labels: Cosmetic or UI, New feature

#6150 Add persistent "player state" datastore, player versions of dock/undock/landing events
  data/libs/Event.lua
  data/libs/Legal.lua
  data/libs/Player.lua
  data/libs/PlayerState.lua
  data/modules/Assassination/Assassination.lua
  data/modules/BreakdownServicing/BreakdownServicing.lua
  data/modules/CargoRun/CargoRun.lua
  data/modules/Combat/Combat.lua
  data/modules/CrewContracts/CrewContracts.lua
  data/modules/CrimeTracking/CrimeTracking.lua
  data/modules/Debug/DebugRPG.lua
  data/modules/Debug/DebugShip.lua
  data/modules/DeliverPackage/DeliverPackage.lua
  data/modules/DonateToCranks/DonateToCranks.lua
  data/modules/FindPerson/FindPerson.lua
  data/modules/FlightLog/FlightLog.lua
  data/modules/FuelClub/FuelClub.lua
  data/modules/GoodsTrader/GoodsTrader.lua
  data/modules/PolicePatrol/PolicePatrol.lua
  data/modules/Rondel/Rondel.lua
  data/modules/Scoop/Scoop.lua
  data/modules/Scout/Scout.lua
  data/modules/SearchRescue/SearchRescue.lua
  data/modules/SecondHand/SecondHand.lua
  data/modules/SoldOut/SoldOut.lua
  data/modules/StationRefuelling/StationRefuelling.lua
  data/modules/Taxi/Taxi.lua
  data/pigui/libs/commodity-market.lua
  data/pigui/libs/equipment-outfitter.lua
  data/pigui/libs/ship-equipment.lua
  data/pigui/modules/info-view/02-personal-info.lua
  data/pigui/modules/info-view/03-econ-trade.lua
  data/pigui/modules/info-view/05-crew.lua
  data/pigui/modules/new-game-window/class.lua
  data/pigui/modules/new-game-window/crew.lua
  data/pigui/modules/station-view/01-lobby.lua
  data/pigui/modules/station-view/04-shipMarket.lua
  data/pigui/modules/station-view/06-shipRepairs.lua
  data/pigui/modules/station-view/07-police.lua
  data/pigui/views/station-view.lua
  src/Game.cpp
  src/Player.cpp
  src/Player.h
  src/Ship.cpp
  src/Ship.h
  src/SpaceStation.cpp
  src/WorldView.cpp
Labels: Lua API

#6153 Support "custom only" station types
  src/SpaceStationType.cpp
  src/SpaceStationType.h
Labels: New feature, Bite-sized

#6154 Add System and Trade Route Bookmark Interface
  data/lang/ui-core/en.json
  data/pigui/libs/forwarded.lua
  data/pigui/libs/modal-win.lua
  data/pigui/libs/sidebar.lua
  data/pigui/modules/sidebar/bookmarks.lua
  data/pigui/modules/system-econ-view.lua
  data/pigui/styles.lua
  data/pigui/themes/default.lua
  data/pigui/views/map-sector-view.lua
  src/lua/LuaPiGui.cpp
  src/pigui/Widgets.cpp
Labels: Cosmetic or UI, New feature

#6187 Minor Terrain files cleanup
  src/terrain/Terrain.cpp
  src/terrain/Terrain.h
  src/terrain/TerrainColorDeadWithWater.cpp
  src/terrain/TerrainFeature.cpp
Labels: Cleanup, C++ code
