Repository pioneerspacesim/pioneer, pull requests merged in 2025-02, with the labels that each got.

#6034 Small fixes
  AUTHORS.txt
  contrib/atomic_queue/atomic_queue.h
  contrib/atomic_queue/defs.h
  data/icons/manufacturer/mandarava-csepel.png
  data/libs/EquipType.lua
  data/modules/Equipment/Types.lua
  data/pigui/modules/new-game-window/class.lua
  data/ships/vatakara.json
  data/textures/decals/mandarava-csepel.dds
  src/ship/PlayerShipController.cpp
Labels: Bug fix

#6035 Final cleanup fixes before release
  data/modules/Assassination/Assassination.lua
  data/modules/SecondHand/SecondHand.lua
  data/modules/TradeShips/Trader.lua
Labels: Bug fix

#6045 Replace `texture2D()` with `texture()`
  data/shaders/opengl/planetrings.frag
Labels: Bug fix, Rendering

#6061 Fixing tail Malabar/Vatakara stabilizer decals
  data/models/ships/malabar/malabar_hi.dae
  data/models/ships/malabar/vatakara_hi.dae
Labels: Bug fix, Art

#5995 Conform to C.128, aka: Virtual functions should specify exactly one of virtual, override, or final
  src/Background.cpp
  src/Beam.h
  src/Body.h
  src/BodyComponent.h
  src/CargoBody.h
  src/DynamicBody.h
  src/FaceParts.cpp
  src/GasGiant.h
  src/GeoSphere.h
  src/HyperspaceCloud.h
  src/JobQueue.h
  src/Missile.h
  src/ModelBody.h
  src/ObjectViewerView.h
  src/Planet.h
  src/Projectile.h
  src/RefCounted.h
  src/Ship.h
  src/ShipCockpit.h
  src/SpaceStation.h
  src/Star.h
  src/TerrainBody.h
  src/collider/BVHTree.h
  src/core/TaskGraph.cpp
  src/editor/ViewportWindow.h
  src/graphics/Material.h
  src/graphics/dummy/MaterialDummy.h
  src/graphics/dummy/RenderTargetDummy.h
  src/graphics/dummy/RendererDummy.h
  src/graphics/dummy/TextureDummy.h
  src/graphics/dummy/UniformBufferDummy.h
  src/graphics/dummy/VertexBufferDummy.h
  src/graphics/opengl/MaterialGL.h
  src/graphics/opengl/RenderTargetGL.h
  src/graphics/opengl/RendererGL.h
  src/graphics/opengl/TextureGL.h
  src/graphics/opengl/VertexBufferGL.h
  src/lua/LuaBodyComponent.h
  src/modelcompiler.cpp
  src/pigui/PiGui.cpp
  src/scenegraph/BinaryConverter.cpp
  src/scenegraph/CollisionGeometry.h
  src/scenegraph/Group.h
  src/scenegraph/LOD.h
  src/scenegraph/MatrixTransform.h
  src/scenegraph/StaticGeometry.h
  src/scenegraph/Tag.h
  src/scenegraph/Thruster.h
  src/ship/CameraController.h
  src/sound/Sound.cpp
Labels: Cleanup, C++ code

#6059 Store AtmosphereParameters in BaseSphere, calculate with material setup
  src/BaseSphere.h
  src/GasGiant.cpp
  src/GeoSphere.cpp
Labels: Cleanup, C++ code

#6054 Lodos normal re-fix
  AUTHORS.txt
  data/models/ships/lodos/lodos-hi.dae
Labels: Art, Model system

#6063 Change modelcompiler single model filepathing, change Editor location for MSVC
  src/editor/CMakeLists.txt
  src/modelcompiler.cpp
Labels: C++ code

#6073 Fix lighting on models that use normal maps
  src/graphics/opengl/VertexBufferGL.cpp
Labels: Bug fix, Model system

#6067 Make Sphere3D/Icosphere reserve space better
  src/BaseSphere.cpp
  src/BaseSphere.h
  src/GasGiant.cpp
  src/GasGiant.h
  src/ObjectViewerView.cpp
  src/Pi.cpp
  src/TerrainBody.cpp
  src/TerrainBody.h
  src/graphics/Drawables.cpp
  src/graphics/Drawables.h
  src/lua/LuaEngine.cpp
Labels: C++ code, Rendering
