Repository pioneerspacesim/pioneer, pull requests merged in 2025-01, with the labels that each got.

#5985 Noise detail texture sampling for gas giant rings
  data/shaders/opengl/lib.glsl
  data/shaders/opengl/planetrings.frag
  data/shaders/opengl/planetrings.shaderdef
  data/textures/ring_noise.png
  src/Planet.cpp
  src/Planet.h
Labels: Bug fix, C++ code, Rendering

#6009 Fix several minor bugs
  data/libs/Ship.lua
  data/modules/Debug/DebugShip.lua
  data/modules/MissionUtils/ShipBuilder.lua
  data/modules/Scoop/Scoop.lua
  data/pigui/libs/notification.lua
  src/galaxy/StarSystemGenerator.cpp
Labels: Bug fix, Bite-sized

#6008 Add four new cultures
  data/culture/culture.lua
  data/culture/eu.lua
  data/culture/fil.lua
  data/culture/hy.lua
  data/culture/se.lua
  data/culture/sq.lua
Labels: Savegame bump

#6013 Add support for required slots, validate shipdefs on startup
  data/libs/EquipSet.lua
  data/libs/EquipType.lua
  data/libs/Event.lua
  data/libs/HullConfig.lua
  data/libs/utils.lua
  data/meta/ShipDef.lua
  data/modules/Debug/CheckShipData.lua
  data/modules/Debug/DebugLoader.lua
  data/modules/Debug/DebugShip.lua
  data/modules/Equipment/Internal.lua
  data/modules/MissionUtils/ShipBuilder.lua
  data/pigui/libs/equipment-outfitter.lua
  data/pigui/libs/notification.lua
  data/pigui/libs/ship-equipment.lua
  data/pigui/modules/new-game-window/class.lua
  data/pigui/modules/station-view/04-shipMarket.lua
  data/pigui/views/debug.lua
  src/Pi.cpp
  src/lua/LuaShipDef.cpp
Labels: Design, New feature, Tools

#6019 Add automated ship JSON import
  .github/workflows/import-ships.yml
  scripts/notion-import/.gitignore
  scripts/notion-import/notion-import.mjs
  scripts/notion-import/package.json
Labels: Tools

#6024 More bugfixes and improvements
  data/factions/079_Tolisian_Scientific_Community.lua
  data/modules/Debug/CheckShipData.lua
  data/pigui/views/debug.lua
  data/pigui/views/mainmenu.lua
  src/Background.cpp
  src/galaxy/StarSystemGenerator.cpp
Labels: Bug fix, Bite-sized

#6027 Improve Naval and Smart missiles
  data/libs/EquipType.lua
  data/libs/Ship.lua
  data/meta/CoreObject/Ship.meta.lua
  data/modules/Debug/DebugShip.lua
  data/modules/Equipment/Weapons.lua
  data/pigui/modules/equipment.lua
  src/Missile.cpp
  src/Missile.h
  src/Player.cpp
  src/Player.h
  src/Ship.cpp
  src/Ship.h
  src/ShipType.cpp
  src/ShipType.h
  src/lua/LuaShip.cpp
  src/ship/GunManager.cpp
  src/ship/GunManager.h
Labels: Design, New feature

#6026 New hyperdrive algorithms and internal hyperfuel tanks
  data/lang/ui-core/en.json
  data/libs/EquipSet.lua
  data/libs/EquipType.lua
  data/libs/HullConfig.lua
  data/libs/Ship.lua
  data/meta/CoreObject/Body.meta.lua
  data/modules/Debug/CheckShipData.lua
  data/modules/Debug/DebugRPG.lua
  data/modules/Equipment/Hyperdrive.lua
  data/modules/MissionUtils/OutfitRules.lua
  data/modules/MissionUtils/ShipBuilder.lua
  data/modules/MissionUtils/ShipTemplates.lua
  data/modules/SearchRescue/SearchRescue.lua
  data/modules/TradeShips/Events.lua
  data/modules/TradeShips/Flow.lua
  data/modules/TradeShips/Trader.lua
  data/pigui/modules/hyperjump-planner.lua
  data/pigui/modules/info-view/01-ship-info.lua
  data/pigui/modules/info-view/03-econ-trade.lua
  data/pigui/modules/station-view/01-lobby.lua
  data/pigui/modules/station-view/04-shipMarket.lua
  data/pigui/views/map-sector-view.lua
Labels: New feature

#6032 Fix bugs, expand equipment coverage, add detailed stats for equipment
  COMPILING.txt
  data/lang/equipment-core/en.json
  data/libs/EquipType.lua
  data/libs/Equipment.lua
  data/modules/Assassination/Assassination.lua
  data/modules/Equipment/Hyperdrive.lua
  data/modules/Equipment/Internal.lua
  data/modules/Equipment/Stats.lua
  data/modules/Equipment/Types.lua
  data/modules/Equipment/Utility.lua
  data/modules/Equipment/Weapons.lua
  data/modules/TradeShips/Trader.lua
  data/pigui/modules/new-game-window/class.lua
  data/pigui/modules/station-view/04-shipMarket.lua
  pioneer-default.code-workspace
Labels: Design, Bug fix
