Repository pioneerspacesim/pioneer, pull requests merged in 2025-03, with the labels that each got.

#6083 Read/write save games from/to the savefiles folder
  src/savegamedump.cpp
Labels: Bug fix, C++ code, Tools

#6072 Update ubuntu version 20.04 -> 22.04 for build
  .github/workflows/build-ci.yml
Labels: Build

#6069 Paint Shop - Randomize colors
  data/lang/ui-core/en.json
  data/pigui/modules/station-view/06-shipRepairs.lua
Labels: Cosmetic or UI
